name: Build Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest version tag
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v1.0.${{ github.run_number }}")
          echo "Latest version: $VERSION"
          echo "$VERSION" > version.txt  # This writes the version to version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt  # Ensure this is the correct artifact path

      - name: Increment version using GitHub Actions run number
        id: increment_version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "New version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push new version tag
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin "refs/tags/${{ env.VERSION }}")
          if [ -z "$TAG_EXISTS" ]; then
            git tag ${{ env.VERSION }}
            git push origin ${{ env.VERSION }}
          else
            echo "Tag ${{ env.VERSION }} already exists on remote. Skipping tag creation."
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            nutzkiller/weather-app:latest
            nutzkiller/weather-app:${{ env.VERSION }}
