name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read current version
        id: get_version
        run: |
          # Check if the version file exists
          if [[ -f version.txt ]]; then
            VERSION=$(cat version.txt)
          else
            VERSION="1.0.0" # Default if no version file exists
          fi
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          # Increment the version number
          IFS='.' read -r -a version_parts <<< "${{ env.VERSION }}"
          patch=${version_parts[2]}
          patch=$((patch + 1)) # Increment the patch version
          new_version="${version_parts[0]}.${version_parts[1]}.$patch"
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Update version file
        run: |
          echo ${{ env.VERSION }} > version.txt
          git add version.txt
          git commit -m "Bump version to ${{ env.VERSION }}"
          git push

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            nutzkiller/weather-app:latest
            nutzkiller/weather-app:${{ env.VERSION }}
